In [25]:
import requests
import pandas as pd

url = "https://income-by-zipcode.p.rapidapi.com/zipcode"

zipcode_list = [98052, 98012, 99301,98103,98682]
querystring = {"zip":zipcode_list}
#querystring = [{'zip:432143'}, {"zip:L32434"}]

headers = {
    'x-rapidapi-key': "cca8656532msh57bc412fbd77850p1ae9eejsna121bac25363",
    'x-rapidapi-host': "income-by-zipcode.p.rapidapi.com"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

[{"income_data":{"Households":26876,"Income100kTo150k":5924,"Income150kTo200k":4262,"Income25To44Years":142459,"Income25To44YearsError":5569,"Income25kTo50k":2614,"Income45To64Years":140486,"Income45To64YearsError":11129,"Income50kTo75k":2731,"Income65YearsAndOver":56111,"Income65YearsAndOverError":9240,"Income75kTo100k":2716,"IncomeAbove200k":6569,"IncomeLessThan25k":2060,"IncomeUnder25Years":62600,"IncomeUnder25YearsError":35636,"IncomeUnder35YearsOver100k":5291,"MeanIncome":152306,"MeanIncomeError":4827,"MedianHouseholdIncome":125287,"MedianHouseholdIncomeError":3673,"PerCapitaIncome":61149,"PerCapitaIncomeError":2259,"PercentIncomeOver200K":24.4,"PercentIncomeOver200KError":1.5,"State":"WA","Zipcode":"98052"},"zipcode":"98052"},{"income_data":{"Households":23593,"Income100kTo150k":5729,"Income150kTo200k":3419,"Income25To44Years":114554,"Income25To44YearsError":4998,"Income25kTo50k":2747,"Income45To64Years":110028,"Income45To64YearsError":9446,"Income50kTo75k":3577,"Income65YearsAndOver":62385,"Income65YearsAndOverError":7754,"Income75kTo100k":3623,"IncomeAbove200k":2850,"IncomeLessThan25k":1648,"IncomeUnder25Years":54837,"IncomeUnder25YearsError":12598,"IncomeUnder35YearsOver100k":3026,"MeanIncome":118189,"MeanIncomeError":3544,"MedianHouseholdIncome":101652,"MedianHouseholdIncomeError":4611,"PerCapitaIncome":43828,"PerCapitaIncomeError":1340,"PercentIncomeOver200K":12.1,"PercentIncomeOver200KError":1.4,"State":"WA","Zipcode":"98012"},"zipcode":"98012"},{"income_data":{"Households":23461,"Income100kTo150k":4090,"Income150kTo200k":1076,"Income25To44Years":65278,"Income25To44YearsError":5465,"Income25kTo50k":5526,"Income45To64Years":71250,"Income45To64YearsError":7052,"Income50kTo75k":4824,"Income65YearsAndOver":47851,"Income65YearsAndOverError":9161,"Income75kTo100k":3392,"IncomeAbove200k":996,"IncomeLessThan25k":3557,"IncomeUnder25Years":37009,"IncomeUnder25YearsError":6707,"IncomeUnder35YearsOver100k":1364,"MeanIncome":78325,"MeanIncomeError":3480,"MedianHouseholdIncome":63020,"MedianHouseholdIncomeError":2492,"PerCapitaIncome":24457,"PerCapitaIncomeError":977,"PercentIncomeOver200K":4.2,"PercentIncomeOver200KError":1.1,"State":"WA","Zipcode":"99301"},"zipcode":"99301"},{"income_data":{"Households":24438,"Income100kTo150k":5038,"Income150kTo200k":2884,"Income25To44Years":109855,"Income25To44YearsError":6294,"Income25kTo50k":3329,"Income45To64Years":115032,"Income45To64YearsError":12300,"Income50kTo75k":3622,"Income65YearsAndOver":59814,"Income65YearsAndOverError":11070,"Income75kTo100k":3152,"IncomeAbove200k":4198,"IncomeLessThan25k":2215,"IncomeUnder25Years":60521,"IncomeUnder25YearsError":12572,"IncomeUnder35YearsOver100k":3977,"MeanIncome":124504,"MeanIncomeError":4439,"MedianHouseholdIncome":99048,"MedianHouseholdIncomeError":4864,"PerCapitaIncome":60391,"PerCapitaIncomeError":2032,"PercentIncomeOver200K":17.2,"PercentIncomeOver200KError":1.3,"State":"WA","Zipcode":"98103"},"zipcode":"98103"},{"income_data":{"Households":19829,"Income100kTo150k":3700,"Income150kTo200k":1230,"Income25To44Years":81616,"Income25To44YearsError":3153,"Income25kTo50k":3873,"Income45To64Years":76029,"Income45To64YearsError":6070,"Income50kTo75k":4202,"Income65YearsAndOver":54482,"Income65YearsAndOverError":8204,"Income75kTo100k":3633,"IncomeAbove200k":809,"IncomeLessThan25k":2382,"IncomeUnder25Years":45089,"IncomeUnder25YearsError":6257,"IncomeUnder35YearsOver100k":1371,"MeanIncome":82910,"MeanIncomeError":2321,"MedianHouseholdIncome":71519,"MedianHouseholdIncomeError":2031,"PerCapitaIncome":28861,"PerCapitaIncomeError":884,"PercentIncomeOver200K":4.1,"PercentIncomeOver200KError":0.8,"State":"WA","Zipcode":"98682"},"zipcode":"98682"}]

In [26]:
# Convert JSON string to a dictionary
income_data = response.json()

In [27]:
income_data

[{'income_data': {'Households': 26876,
   'Income100kTo150k': 5924,
   'Income150kTo200k': 4262,
   'Income25To44Years': 142459,
   'Income25To44YearsError': 5569,
   'Income25kTo50k': 2614,
   'Income45To64Years': 140486,
   'Income45To64YearsError': 11129,
   'Income50kTo75k': 2731,
   'Income65YearsAndOver': 56111,
   'Income65YearsAndOverError': 9240,
   'Income75kTo100k': 2716,
   'IncomeAbove200k': 6569,
   'IncomeLessThan25k': 2060,
   'IncomeUnder25Years': 62600,
   'IncomeUnder25YearsError': 35636,
   'IncomeUnder35YearsOver100k': 5291,
   'MeanIncome': 152306,
   'MeanIncomeError': 4827,
   'MedianHouseholdIncome': 125287,
   'MedianHouseholdIncomeError': 3673,
   'PerCapitaIncome': 61149,
   'PerCapitaIncomeError': 2259,
   'PercentIncomeOver200K': 24.4,
   'PercentIncomeOver200KError': 1.5,
   'State': 'WA',
   'Zipcode': '98052'},
  'zipcode': '98052'},
 {'income_data': {'Households': 23593,
   'Income100kTo150k': 5729,
   'Income150kTo200k': 3419,
   'Income25To44Years': 114554,
   'Income25To44YearsError': 4998,
   'Income25kTo50k': 2747,
   'Income45To64Years': 110028,
   'Income45To64YearsError': 9446,
   'Income50kTo75k': 3577,
   'Income65YearsAndOver': 62385,
   'Income65YearsAndOverError': 7754,
   'Income75kTo100k': 3623,
   'IncomeAbove200k': 2850,
   'IncomeLessThan25k': 1648,
   'IncomeUnder25Years': 54837,
   'IncomeUnder25YearsError': 12598,
   'IncomeUnder35YearsOver100k': 3026,
   'MeanIncome': 118189,
   'MeanIncomeError': 3544,
   'MedianHouseholdIncome': 101652,
   'MedianHouseholdIncomeError': 4611,
   'PerCapitaIncome': 43828,
   'PerCapitaIncomeError': 1340,
   'PercentIncomeOver200K': 12.1,
   'PercentIncomeOver200KError': 1.4,
   'State': 'WA',
   'Zipcode': '98012'},
  'zipcode': '98012'},
 {'income_data': {'Households': 23461,
   'Income100kTo150k': 4090,
   'Income150kTo200k': 1076,
   'Income25To44Years': 65278,
   'Income25To44YearsError': 5465,
   'Income25kTo50k': 5526,
   'Income45To64Years': 71250,
   'Income45To64YearsError': 7052,
   'Income50kTo75k': 4824,
   'Income65YearsAndOver': 47851,
   'Income65YearsAndOverError': 9161,
   'Income75kTo100k': 3392,
   'IncomeAbove200k': 996,
   'IncomeLessThan25k': 3557,
   'IncomeUnder25Years': 37009,
   'IncomeUnder25YearsError': 6707,
   'IncomeUnder35YearsOver100k': 1364,
   'MeanIncome': 78325,
   'MeanIncomeError': 3480,
   'MedianHouseholdIncome': 63020,
   'MedianHouseholdIncomeError': 2492,
   'PerCapitaIncome': 24457,
   'PerCapitaIncomeError': 977,
   'PercentIncomeOver200K': 4.2,
   'PercentIncomeOver200KError': 1.1,
   'State': 'WA',
   'Zipcode': '99301'},
  'zipcode': '99301'},
 {'income_data': {'Households': 24438,
   'Income100kTo150k': 5038,
   'Income150kTo200k': 2884,
   'Income25To44Years': 109855,
   'Income25To44YearsError': 6294,
   'Income25kTo50k': 3329,
   'Income45To64Years': 115032,
   'Income45To64YearsError': 12300,
   'Income50kTo75k': 3622,
   'Income65YearsAndOver': 59814,
   'Income65YearsAndOverError': 11070,
   'Income75kTo100k': 3152,
   'IncomeAbove200k': 4198,
   'IncomeLessThan25k': 2215,
   'IncomeUnder25Years': 60521,
   'IncomeUnder25YearsError': 12572,
   'IncomeUnder35YearsOver100k': 3977,
   'MeanIncome': 124504,
   'MeanIncomeError': 4439,
   'MedianHouseholdIncome': 99048,
   'MedianHouseholdIncomeError': 4864,
   'PerCapitaIncome': 60391,
   'PerCapitaIncomeError': 2032,
   'PercentIncomeOver200K': 17.2,
   'PercentIncomeOver200KError': 1.3,
   'State': 'WA',
   'Zipcode': '98103'},
  'zipcode': '98103'},
 {'income_data': {'Households': 19829,
   'Income100kTo150k': 3700,
   'Income150kTo200k': 1230,
   'Income25To44Years': 81616,
   'Income25To44YearsError': 3153,
   'Income25kTo50k': 3873,
   'Income45To64Years': 76029,
   'Income45To64YearsError': 6070,
   'Income50kTo75k': 4202,
   'Income65YearsAndOver': 54482,
   'Income65YearsAndOverError': 8204,
   'Income75kTo100k': 3633,
   'IncomeAbove200k': 809,
   'IncomeLessThan25k': 2382,
   'IncomeUnder25Years': 45089,
   'IncomeUnder25YearsError': 6257,
   'IncomeUnder35YearsOver100k': 1371,
   'MeanIncome': 82910,
   'MeanIncomeError': 2321,
   'MedianHouseholdIncome': 71519,
   'MedianHouseholdIncomeError': 2031,
   'PerCapitaIncome': 28861,
   'PerCapitaIncomeError': 884,
   'PercentIncomeOver200K': 4.1,
   'PercentIncomeOver200KError': 0.8,
   'State': 'WA',
   'Zipcode': '98682'},
  'zipcode': '98682'}]

In [49]:
# Create Dataframe #income by age and income X and Y #medium income for a 45yr old
#print(income_data[0])
data = income_data[0]['income_data']
#print(data)
income_df = pd.json_normalize(data)[['Income25kTo50k', 'Income50kTo75k','Income75kTo100k', 'Income100kTo150k', 'Income150kTo200k']]
# income_df.to_csv('income_zipcode.csv')
income_df.head()

,Income25kTo50k,Income50kTo75k,Income75kTo100k,Income100kTo150k,Income150kTo200k
0,2614,2731,2716,5924,4262